[MAIN]
nEpochs = 10
nBatchSize = 8
nPatience = 3
nKFolds = 2
bCategorical = false
sDevice = cpu
# Стабільність навчання (для вирішення NaN loss на GPU)
fLearningRate = 0.001
bGradientClipping = true