[MAIN]
nEpochs = 100
nBatchSize = 64
nPatience = 3
nKFolds = 5
bCategorical = true
sDevice = cpu
# Стабільність навчання (для вирішення NaN loss на GPU)
fLearningRate = 0.001
bGradientClipping = false